import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";
import Script from "./javaScripts/app";
import Script2 from "./javaScripts/particles";
import Script3 from "./javaScripts/countNo";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Travel Portal Development | Travel Website Development</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="particles-js" className={styles.wallpaper}>
        <div className={styles.titleh}>
        <i class="fa fa-bullseye"></i>
        <h1>Travel Portal Development Company</h1>
        <p>
          eWeblink Technology is a leading travel portal development company
          having over 400+ clients globally <br/> We are specialized in travel portal
          development, and integrate various GDS's XML, API's, testing &
          deployment, <br /> we also maintain the travel website for 24/7 technical and
          customer support services.
        </p>
        </div>
      </section>
      {/* ---------------------------------------sticky button----------------------------------------- */}
      <div className={styles.enquari_Btn}>
        <a href="#">
          <Image src="	https://www.eweblink.net/images/send-enquiry.png" width={208} height={60}></Image>
        </a>
      </div>
      <script src="https://apps.elfsight.com/p/platform.js" defer></script>
      <div class="elfsight-app-57e3a3d1-a8e5-485f-8aff-dad16bab283a"></div>
      <script src="//code.tidio.co/ooinjddmro0z2swbvj3901clt3t6xbjz.js" async></script>
      {/* ---------------------------------------sticky button End----------------------------------------- */}
      <section className={styles.experience}>
        <div className={styles.experiencetype}>
          <div className={styles.exTy}>
            <div className={styles.extyimg}><Image src="/country.png" width={71} height={70}></Image></div>
            <div class={styles.counter} data-target="20">0</div>
            <p>20+ Countries</p>
          </div>
          <div className={styles.exTy}>
            <div className="extyimg"><Image src="https://www.eweblink.net/images/icons/website.png" width={90} height={68}></Image></div>
            <div class={styles.counter} data-target="400">0</div>
            <p>400+ Websites</p>
          </div>
          <div className={styles.exTy}>
            <div className="extyimg"><Image src="	https://www.eweblink.net/images/icons/network.png" width={90} height={68}></Image></div>
            <div class={styles.counter} data-target="60">0</div>
            <p>60+ Suppliers</p>
          </div>
          <div className={styles.exTy}>
            <div className="extyimg"><Image src="		https://www.eweblink.net/images/icons/api-partner.png" width={90} height={68}></Image></div>
            <div class={styles.counter} data-target="50">0</div>
            <p>50+ API Partners</p>
          </div>
          <div className={styles.exTy}>
            <div className="extyimg"><Image src="			https://www.eweblink.net/images/icons/experience.png" width={90} height={68}></Image></div>
            <div class={styles.counter} data-target="10">0</div>
            <p>10+ Years <br /> Experience</p>
          </div>
          <div className={styles.exTy}>
            <div className="extyimg"><Image src="		https://www.eweblink.net/images/icons/application.png" width={90} height={68}></Image></div>
            <div class={styles.counter} data-target="100">0</div>
            <p>100+ Features</p>
          </div>
        </div>
      </section>
      <section className={styles.about_sec}>
        <div className={styles.about_conatainer}>
        <h2>TRAVEL WEBSITE DEVELOPMENT COMPANY</h2>
        <p>
        If you have been looking for <strong>Travel Website Development Company</strong> to build and design exceptionally appealing and aesthetic website, you’re at right place. eWeblink Technology, being one of the renowned names in Travel Industry specializes in <a href="https://www.eweblink.net/online-travel-website-designing.html">travel website design and development.</a> Since time immemorial, we’ve been providing out of the way <a href="https://www.eweblink.net/travel-portal-solution.html">travel portal solutions</a> and administrative resources integrating new trends and technology to aid you thrive in your business. With 10+ years of quality experience and with customer growth, our only MOTTO is to build high-quality, eye-catchy, responsive, and user-friendly custom travel website having integration with latest technologies.
        </p>
        <p>
        The team at eWeblink Technology, has immense knowledge when it comes to creating <strong>beautiful travel & tourism website design and portal development in Delhi. Our web developers</strong> have profound technical know-how and passion for building travel specific websites. Moreover, we also offer fully functional <strong>tourism portal development services</strong> depending upon your custom requirements. To stay ahead and competent in international travel industry, we’re here to GROW your business with our top-notch <a href="https://www.eweblink.net/website-development-company.html" target={"_blank"}>web development services.</a>
        </p>
        </div>
      </section>
    </div>
  );
}
